baseurl: "/"
url: https://zimsa.org.zw
title: Zimsa
timezone: UTC
description: "The official website of the Zimbabwe Medical Students Association (ZIMSA) is a comprehensive platform dedicated to empowering medical students across Zimbabwe. It serves as a hub for resources, events, and networking opportunities that support professional growth and academic excellence. Explore updates on workshops, conferences, and outreach programs designed to enhance medical education and healthcare delivery. The site also showcases ZIMSA's departments, leadership structure, and initiatives aimed at fostering collaboration and community impact among future healthcare professionals."
author: "Zimsa"
email: "pro@zimsa.org.zw"
phone: "+263 77 189 0416"
address: "1234 New Age Street, Harare, Zimbabwe"
social:
  twitter: "https://twitter.com/zimsa"
  facebook: "https://facebook.com/zimsa"
  instagram: "https://instagram.com/zimsa"
  whatsapp: "https://wa.me/263771890416"
  linkedin: "https://linkedin.com/zimsa"
