---
title: Zimsa
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Zimsa is the home for all the medical students in Zimbabwe. Take a look
  and see what we are up to!
baseurl: "/"
url: https://zimsa.org
twitter_username: jekyllrb
github_username: jekyll
plugins:
- jekyll-feed
